spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Baku

download:
  token:
    expiry: 10

jwt:
  token:
    validity: 7200000
    refresh: 2592000000
    prefix: Bearer
  signing:
    key: ${SIGNING_KEY}
  authorities:
    key: roles
  header:
    string: Authorization



