spring:
  #  jpa:
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods: "*"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tezish?serverTimezone=Asia/Baku&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku
  jackson:
    time-zone: Asia/Baku

download:
  token:
    expiry: 3

jwt:
  token:
    validity: 7200000
    refresh: 2592000000
    prefix: Bearer
  signing:
    key: dGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNo
  authorities:
    key: roles
  header:
    string: Authorization



