spring:
  #  jpa:
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods: "*"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/tezish?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

download:
  token:
    expiry: 10

jwt:
  token:
    validity: 7200000
    refresh: 2592000000
    prefix: Bearer
  signing:
    key: dGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNodGV6aXNo
  authorities:
    key: roles
  header:
    string: Authorization



